services:
  - type: web
    name: quicksave
    env: native
    buildCommand: |
      npm install
      pip3 install -U yt-dlp
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: YTDLP_PATH
        value: /usr/local/bin/yt-dlp
